Import in Numpy lib

In [1]:
import numpy as np

Matrix Addition

Two matrix can be add when the shape is same

In [7]:
A=np.array([[4,5],[12,12]])

B=np.array([[13,14],[4,5]])

In [8]:
print(A)

[[ 4  5]
 [12 12]]


In [9]:
print(B)

[[13 14]
 [ 4  5]]


In [10]:
A.shape

(2, 2)

In [11]:
B.shape

(2, 2)

Adding two matrix

In [15]:
sum = A + B

In [16]:
print(sum)

[[17 19]
 [16 17]]


In [23]:
# Create two matrix with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(10,size=(3,3))
print(matrix_1)

[[8 9 5]
 [5 8 7]
 [8 2 1]]


In [24]:
print(matrix_2)

[[6 1 6]
 [5 2 1]
 [1 3 1]]


In [25]:
sum =np.add(matrix_1,matrix_2)

In [26]:
print(sum)

[[14 10 11]
 [10 10  8]
 [ 9  5  2]]


Matrix Subtraction

In [27]:
A =np.array([[4,5],[12,12]])

B =np.array([[13,14],[4,5]])

In [30]:
print(A)

[[ 4  5]
 [12 12]]


In [31]:
print(B)

[[13 14]
 [ 4  5]]


In [32]:
diffrence = A-B

In [33]:
print(diffrence)

[[-9 -9]
 [ 8  7]]


In [34]:
# Create two matrix with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(10,size=(3,3))
print(matrix_1)

[[4 7 4]
 [0 6 7]
 [6 7 8]]


In [35]:
print(matrix_2)

[[0 9 0]
 [7 7 2]
 [7 5 1]]


In [37]:
diffrence = np.subtract(matrix_1,matrix_2)

In [38]:
print(diffrence)

[[ 4 -2  4]
 [-7 -1  5]
 [-1  2  7]]


Multiplying a matrix to a sclaer

In [41]:
x = 5

y=np.random.randint(10,size=(3,3))

In [42]:
print(y)

[[0 6 2]
 [6 4 8]
 [5 3 5]]


In [43]:
product = np.multiply(x,y)

In [44]:
print(product)

[[ 0 30 10]
 [30 20 40]
 [25 15 25]]


Multiplying 2 matrix 

In [46]:
x=np.random.randint(10,size=(3,3))
y=np.random.randint(10,size=(3,3))

In [47]:
print(x)

[[7 0 7]
 [9 8 7]
 [3 2 3]]


In [48]:
print(y)

[[7 0 0]
 [1 4 5]
 [8 6 8]]


In [52]:
product = np.dot(x,y)

In [53]:
print(product)

[[105  42  56]
 [127  74  96]
 [ 47  26  34]]


Element wise Matrix multiplication

In [54]:
x=np.random.randint(10,size=(3,3))
y=np.random.randint(10,size=(3,3))

In [55]:
print(x)

[[6 7 5]
 [4 7 2]
 [4 9 4]]


In [57]:
print(y)

[[1 7 5]
 [9 8 5]
 [5 0 5]]


In [58]:
product = np.multiply(x,y)

In [59]:
print(product)

[[ 6 49 25]
 [36 56 10]
 [20  0 20]]
