In [1]:
#numpy means numerical python
import numpy as np

Creating a Matrix using numpy

In [3]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
#shape of matrix
matrix_1.shape

(2, 2)

In [6]:
matrix_2=np.array([[2,3,4],[45,67,76],[20,15,19]])
print(matrix_2)

[[ 2  3  4]
 [45 67 76]
 [20 15 19]]


In [8]:
#shape of matrix
matrix_2.shape

(3, 3)

Creating Matrix With Random Values

In [11]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.57861441 0.29885251 0.71921393]
 [0.12253882 0.98499731 0.89627144]
 [0.69403857 0.72743243 0.97214115]]


In [14]:
#creating matrix with integers
random_matrix=np.random.randint(100,size=(3,5))
print(random_matrix)

[[48 37 36 37 74]
 [92 34 57 17  1]
 [92 53 71 15  7]]


Matrix with all the value is one

In [16]:
matrix_1=np.ones((2,3))
print(matrix_1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#For Zeros in integers also is null matrix
matrix_1=np.zeros((2,3),dtype=int)
print(matrix_1)

[[0 0 0]
 [0 0 0]]


In [19]:
matrix_1=np.ones((20,30),dtype=int)
print(matrix_1)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

Identity Matrix

In [20]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
identity_matrix=np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [25]:
#Random integer value
a=np.random.randint(100,size=(3,3))
print(a)

[[ 1 93 94]
 [ 8 88 27]
 [30 40 13]]


In [28]:
transpose_of_a=np.transpose(a)

In [29]:
print(transpose_of_a)

[[ 1  8 30]
 [93 88 40]
 [94 27 13]]
